# Default initial positions for motoman_gp4's ros2_control fake system

initial_positions:
  group_1/joint_1: 0
  group_1/joint_2: 0
  group_1/joint_3: 0
  group_1/joint_4: 0
  group_1/joint_5: 0
  group_1/joint_6: 0