# joint_limits.yaml allows the dynamics properties specified in the URDF to be overwritten or augmented as needed

# For beginners, we downscale velocity and acceleration limits.
# You can always specify higher scaling factors (<= 1.0) in your motion requests.  # Increase the values below to 1.0 to always move at maximum speed.
default_velocity_scaling_factor: 0.1
default_acceleration_scaling_factor: 0.1

# Specific joint properties can be changed with the keys [max_position, min_position, max_velocity, max_acceleration]
# Joint limits can be turned off with [has_velocity_limits, has_acceleration_limits]
joint_limits:
  group_1/joint_1:
    has_velocity_limits: true
    max_velocity: 8.1157810217736319
    has_acceleration_limits: false
    max_acceleration: 0
  group_1/joint_2:
    has_velocity_limits: true
    max_velocity: 8.1157810217736319
    has_acceleration_limits: false
    max_acceleration: 0
  group_1/joint_3:
    has_velocity_limits: true
    max_velocity: 9.1629785729702302
    has_acceleration_limits: false
    max_acceleration: 0
  group_1/joint_4:
    has_velocity_limits: true
    max_velocity: 9.8611102737679612
    has_acceleration_limits: false
    max_acceleration: 0
  group_1/joint_5:
    has_velocity_limits: true
    max_velocity: 9.8611102737679612
    has_acceleration_limits: false
    max_acceleration: 0
  group_1/joint_6:
    has_velocity_limits: true
    max_velocity: 17.453292519943297
    has_acceleration_limits: false
    max_acceleration: 0