# MoveIt uses this configuration for controller management

moveit_controller_manager: moveit_simple_controller_manager/MoveItSimpleControllerManager

moveit_simple_controller_manager:
  controller_names:
    - Arm_controller

  Arm_controller:
    type: FollowJointTrajectory
    action_ns: follow_joint_trajectory
    default: true
    joints:
      - group_1/joint_1
      - group_1/joint_2
      - group_1/joint_3
      - group_1/joint_4
      - group_1/joint_5
      - group_1/joint_6