# This config file is used by ros2_control
controller_manager:
  ros__parameters:
    update_rate: 100  # Hz

    Arm_controller:
      type: joint_trajectory_controller/JointTrajectoryController


    joint_state_broadcaster:
      type: joint_state_broadcaster/JointStateBroadcaster

Arm_controller:
  ros__parameters:
    joints:
      - group_1/joint_1
      - group_1/joint_2
      - group_1/joint_3
      - group_1/joint_4
      - group_1/joint_5
      - group_1/joint_6
    command_interfaces:
      - position
    state_interfaces:
      - position
      - velocity